# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f1BHauP34tOjWKi32dLvlfk7UHah8S6K
"""

import pandas as pd
import streamlit as st

st.title("A Simple Quadratic Equation Solver")

st.latex(r'''
    X = \frac{-b\pm\sqrt{b^2 - 4ac}}{2a}
    ''')

name = st.text_input("Enter your name"," ")

st.write(f"Hello {name}!")


a = st.number_input("input your a:")
b = st.number_input("input your b:")
c = st.number_input("input your c:")


hasil1 = (-b + ((b**2 - 4*a*c)**0.5)) / (2*a)
hasil2 = (-b - ((b**2 - 4*a*c)**0.5)) / (2*a)


st.write("Maka nilai akar akar persamaan adalah", "X1 = ",hasil1, "dan X2 = ", hasil2)

