# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f1BHauP34tOjWKi32dLvlfk7UHah8S6K
"""

import pandas as pd
import streamlit as st

st.title("A Simple Quadratic Equation Solver")

st.latex(r'''
    a + ar + a r^2 + a r^3 + \cdots + a r^{n-1} =
    \sum_{k=0}^{n-1} ar^k =
    a \left(\frac{1-r^{n}}{1-r}\right)
    ''')

name = st.text_input("Enter your name"," ")

st.write(f"Hello {name}!")

x = st.number_input("input your x:")
y = st.number_input("input your y:")

df = x**2 - 2-y + 17

st.write("hasilnya adalah:", df)

